FirewallDnsName = "pan-fw"
FirewallVmName = "vvPANW"
FirewallVmSize = "Standard_D2s_v3"
FromGatewayLogin = "0.0.0.0/0"
StorageAccountName = "vvstg11"
WebServerDnsName = "pan-web"
location = "uksouth"
resource_group_name = "vvrg12"
